
#-----------------------------------------------------------------------

APP       := Test
TARGET    := HelloWorldClient
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:=

INCLUDE   += 
LIB       += 
CFLAGS    += -std=c++11 
#-----------------------------------------------------------------------
include /home/tarsproto/Test/HelloWorldServer/HelloWorldServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
