
#-----------------------------------------------------------------------

APP       := Test
TARGET    := HelloWorldServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------
include /home/tarsproto/Test/HelloWorldBckendSecondServer/HelloWorldBckendSecondServer.mk
include /home/tarsproto/Test/HelloWorldBackendServer/HelloWorldBackendServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
