
#-----------------------------------------------------------------------

APP       := Test
TARGET    := HttpServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------
include /home/tarsproto/Test/HelloWorldServer/HelloWorldServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
